=== api-evangelist/amazon-neptune/json-schema/amazon-neptune-createmodeltransformjobrequest-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/CreateModelTransformJobRequest",
  "title": "CreateModelTransformJobRequest",
  "type": "object",
  "required": [
    "modelTransformOutputS3Location"
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "dataProcessingJobId": {
      "type": "string",
      "description": "Job ID of the completed data processing job."
    },
    "mlModelTrainingJobId": {
      "type": "string",
      "description": "Job ID of the completed model training job."
    },
    "trainingJobName": {
      "type": "string",
      "description": "Name of a completed SageMaker training job."
    },
    "modelTransformOutputS3Location": {
      "type": "string",
      "description": "S3 location for transform output artifacts."
    },
    "sagemakerIamRoleArn": {
      "type": "string"
    },
    "neptuneIamRoleArn": {
      "type": "string"
    },
    "baseProcessingInstanceType": {
      "type": "string"
    },
    "baseProcessingInstanceVolumeSizeInGB": {
      "type": "integer"
    },
    "subnets": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "securityGroupIds": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "volumeEncryptionKMSKey": {
      "type": "string"
    },
    "s3OutputEncryptionKMSKey": {
      "type": "string"
    },
    "enableInterContainerTrafficEncryption": {
      "type": "boolean",
      "default": true
    },
    "customModelTransformParameters": {
      "type": "object",
      "properties": {
        "sourceS3DirectoryPath": {
          "type": "string"
        },
        "transformEntryPointScript": {
          "type": "string"
        }
      }
    }
  }
}

=== api-evangelist/amazon-neptune/examples/ml-create-model-transform-job-request-example.json
{
  "id": "neptune-cluster-abc123",
  "dataProcessingJobId": "neptune-cluster-abc123",
  "mlModelTrainingJobId": "neptune-cluster-abc123",
  "trainingJobName": "my-neptune-cluster",
  "modelTransformOutputS3Location": "example-string",
  "sagemakerIamRoleArn": "arn:aws:neptune:us-east-1:123456789012:cluster:neptune-1",
  "neptuneIamRoleArn": "arn:aws:neptune:us-east-1:123456789012:cluster:neptune-1",
  "baseProcessingInstanceType": "db.r6g.large",
  "baseProcessingInstanceVolumeSizeInGB": 43,
  "subnets": [
    "example-string"
  ],
  "securityGroupIds": [
    "example-string"
  ],
  "volumeEncryptionKMSKey": "example-string",
  "s3OutputEncryptionKMSKey": "example-string",
  "enableInterContainerTrafficEncryption": true,
  "customModelTransformParameters": {
    "sourceS3DirectoryPath": "example-string",
    "transformEntryPointScript": "example-string"
  }
}
